spring:
  datasource:
    url: jdbc:h2:mem:piggybank
    driverClassName: org.h2.Driver
    username: admin
    password: 04Admin2020!

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
